### ISSUE TITLE
ONLINE PYGAME EXECUTION

### ISSUE THREAD

**Issue by cool-dev-guy** [pygame-web/pygbag#100]
### Discussed in https://github.com/pygame-web/pygbag/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **cool-dev-guy** June  2, 2023</sup>
Hey @pmp-p ,I studied the pygame-web final product of a pygame project and i understood that first there is a GET request to `game_name.apk` and inside it in the `assets` folder i can find a `main.py`,Is it possible to change the code inside `main.py` before its being executed,Or can i make the website run the python code which i stored in a javascript/python variable?</div>

**Comment by pmp-p** [comment]
This is not the purpose of pygbag, this is about using python c-api or use of python compiler at runtime ( compile/eval ). See discussions
