### ISSUE TITLE
feature request / debug , find module that blocks pygbag 

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/pygbag#102]
it would be nice to have a debug tool that executes your code , and finds out if there is any module/ block of code that is blocking pygbag / asyncio ( or why your game has a black screen , even if you are 99.999% sure there is no while True loop  )  ,

**Comment by pmp-p** [comment]
The simulator should be able to do that by launching a thread that will watch if the game loop is giving hand to host or not, but only the main loop is currently implemented ( and not documented).

**Comment by tigercoding56** [comment]
> The simulator should be able to do that by launching a thread that will watch if the game loop is giving hand to host or not, but only the main loop is currently implemented ( and not documented).
there is a simulator ?

**Comment by pmp-p** [comment]
Yes it but it runs only on Linux with [python-wasm-sdk](https://github.com/pygame-web/python-wasm-sdk) installed. This is not a very easy setup, but it is not currently possible to launch a monitoring thread in browser wasm engine so it is the only way i see.

**Comment by tigercoding56** [comment]
> Yes it but it runs only on Linux with [python-wasm-sdk](https://github.com/pygame-web/python-wasm-sdk) installed. This is not a very easy setup, but it is not currently possible to launch a monitoring thread in browser wasm engine so it is the only way i see.
ok    thank you for your help (someone should really add this information to the wiki)
