### ISSUE TITLE
how to import and use self-customized python library

### ISSUE THREAD

**Issue by zjowowen** [pygame-web/pygbag#109]
Hi, 

I am currently making an game environment front-end for demonstrating reinforcement learning algorithms as a huggingface space demo.

What should I do if I want to import a self-customized python library in pygbag?

The game is usually running by simulators.
Simple reinforcement learning games are imported from gym or gym-retro.

For example,
import gym
env=gym.make("some_environment")
image=env.render()
Then, copy the image into pygame and render on the webpage.

"import numpy" is in the main.py when using pygbag.
But I found difficulty in import gym or gym-retro.
Can you give me any suggestions in how to do that?

Thanks!

**Comment by pmp-p** [comment]
Hi, for third party lib support (really when simple/possible, tbh don't expect to much for free from people around or from original authors as porting can be extremelly painfull) you may want to explain your needs here https://github.com/pygame-web/pkg-porting-wasm
