### ISSUE TITLE
Audio repeats in 1-2 second loop when chrome back button is pressed and "are you sure you want to leave changes you made might not be saved" notification shows

### ISSUE THREAD

**Issue by Two119** [pygame-web/pygbag#115]
I was working on a web port for my game when I noticed the audio loops in 1-2 second loop of whatever sound it was currently playing when you press chrome back button and "are you sure you want to leave changes you made might not be saved" notification shows up.

**Comment by pmp-p** [comment]
i think default dialog should always call music.pause() in pygame patched functions before sending the dialog and resume them if the "kill" is aborted.
If kill is not aborted no problem since it would already be paused.

**Comment by pmp-p** [comment]
note that the fix can only deal with mixer.music . Maybe SDL2 sfx can cause trouble. feel tree to reopen after 0.8 in that case
