### ISSUE TITLE
Where am I failing?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [pygame-web/pygbag#123]
When i run my pygame using pygbag i get the following error:

![image](https://github.com/pygame-web/pygbag/assets/10560652/e3936235-1501-4db6-87d1-d79bfd02c6ae)

my ```main.py``` is referring these local modules like this:
![image](https://github.com/pygame-web/pygbag/assets/10560652/e869295e-5bb1-4703-869b-396a939e8612)

I can see all the script files for these modules are included in the apk-file in directory assets (same level as main.py)

![image](https://github.com/pygame-web/pygbag/assets/10560652/f782d76c-51b9-46d3-8cd9-62e29dffc16f)

So it seems to be looking for my own modules in the CDN. 
Should I copy all modules into main.py, so I only have one file?

**Comment by pmp-p** [comment]
We cannot tell from just those screenshots, please provide a github project/page or a itch web.zip archive (--archive) of whole project you give to pygbag.

**Comment by ThorvaldAagaard** [comment]
This repository: https://github.com/ThorvaldAagaard/bridge-with-ben

It is not a complete application, but running ```python main.py``` from the game directory gives:
![image](https://github.com/pygame-web/pygbag/assets/10560652/7c8bb876-b4c8-4efa-8dcb-aad0005d95d9)

Running ```pygbag game``` and then going to http://localhost:8000/?-i gives the CDN-error

web.zip attached it that is easier than cloning my repository
[web.zip](https://github.com/pygame-web/pygbag/files/13060618/web.zip)

**Comment by pmp-p** [comment]
you had some blocking while loops
https://github.com/ThorvaldAagaard/bridge-with-ben/pull/1/files

**Comment by ThorvaldAagaard** [comment]
Thank you.
So on any drawing in a loop remember to sleep to avoid the blocking.

and this is just some information that can be ignored
```
1103: list_imports len(code)=7414 file=None hint=PosixPath('/data/data/game/assets/main.py')
1095: scan_imports hint=PosixPath('/data/data/game/assets/main.py') filename='<stdin>' len(code)=7414 ['table', 'drawing_func', 'player', 'buttons']
1132: repo['-CDN-']='http://localhost:8080/archives/repo/' does not provide want='table'
1132: repo['-CDN-']='http://localhost:8080/archives/repo/' does not provide want='drawing_func'
1132: repo['-CDN-']='http://localhost:8080/archives/repo/' does not provide want='player'
1132: repo['-CDN-']='http://localhost:8080/archives/repo/' does not provide want='buttons'
628: aio.pep0723.check_list env=PosixPath('/usr/lib/python3.11/site-packages') 
```
