### ISSUE TITLE
Pygbag Pygame screen is just black after loading

### ISSUE THREAD

**Issue by Visssarion** [pygame-web/pygbag#133]
After I build my game with following command:
pygbag endless_fusion_web
And after clicking "Ready to start" on localhost:8000 i am being presented with black screen
![image](https://github.com/pygame-web/pygbag/assets/46628714/b7e52706-1fe8-458a-ae42-c25ca1eb5c3a)
When launching main.py on the system itself, game loads just fine.

Here's a link to source code of the project:
https://github.com/Visssarion/endless_fusion/tree/web_version
And here's main file:
https://github.com/Visssarion/endless_fusion/blob/web_version/main.py

**Comment by Visssarion** [comment]
I am using terminal through Pycharm, although doubt that changes anything

**Comment by pmp-p** [comment]
i think in pygame2 lerp() moved as optimized methods for Vector2/3 and those don't require pygame.math import anymore

**Comment by pmp-p** [comment]
also your fullscreen manager is not web compatible
just replace it by a fixed reasonnable screen size ( eg 1024x600 ) and let browser handle hardware scaling

**Comment by Visssarion** [comment]
Thank you so much! I did this and it worked.
When i heard about debug mode i thought about a standart browser console, i did not know there was a proper debug mode.

If I ever make a devlog about development of this (or a video on "how to fix black screen") i will mention about debug mode.
Sorry for inconvinience.
