### ISSUE TITLE
Chess won't launch

### ISSUE THREAD

**Issue by 3004006050** [pygame-web/pygbag#136]
Trying to launch a chess application, and the imports aren't being packaged.  I packaged it with ume_block 0, and stockfish, tkinter, and other imports weren't recognized.
`from math import trunc
from queue import Empty
from tkinter import W
from typing import Counter, Self
from xml.sax.handler import feature_namespace_prefixes
from chessassets.readconfig import read_config
import pygame
import os
import sys
import copy
import time
from stockfish import Stockfish
import asyncio`
![image](https://github.com/pygame-web/pygbag/assets/63968290/ee01c441-b91e-442b-83b8-e652e7de875f)
black screen im having:
![image](https://github.com/pygame-web/pygbag/assets/63968290/ad70e8e7-95a1-4c02-a67d-b44d2b2ce26f)

**Comment by pmp-p** [comment]
hi, tkinter despite its popularity and its authors is not an integral part of python. It is a set of bindings around a GUI library toolkit implemented only for some operating systems and called Tcl/Tk .

Sadly it was not implemented yet for emscripten ( the OS pygbag currently uses ).

it is a porting matter, so your best chance is to open an issue for that in https://github.com/pygame-web/pkg-porting-wasm/issues

i did not check for stockfish but it could be the same problem

**Comment by 3004006050** [comment]
Alright, will do.
