### ISSUE TITLE
Runtime error messages

### ISSUE THREAD

**Issue by lsoaresesilva** [pygame-web/pygbag#141]
Hello, 

I'm able to serve the built index.html generated by pygbag. However, when a runtime error occurs, the message is not shown. In a pure pygame app, it would crash and an exception message will be shown in the cmd. I know about the debug mode, but i can not use it because i'm running my own server.

Any ideas on how to get the error messages from pygbag during game
Execution and without using debug mode?

Thank you

**Comment by pmp-p** [comment]
Telemetry is not provided. You are free to implement your own but if you do so : please do not use pygame-web or pygbag terms. Thank you.
