### ISSUE TITLE
Using ngrok as tunnel

### ISSUE THREAD

**Issue by tungts1101** [pygame-web/pygbag#145]
To be clear, I have no problem using `pygbag` to run wasm in my local browser. My next target is sharing with my friends. Normally I use `ngrok` as a tunnel for fast sharing, however, it shows no error in this situation and renders a blank form like the picture below. Does anyone get the same problem?

![image](https://github.com/pygame-web/pygbag/assets/37470762/d136f4ca-417c-4a78-aa15-cdd494c02e73)

**Comment by pmp-p** [comment]
To be clear, i have no idea what is ngrok ( and maybe others reading are like me)

 Please explain what it is ( and what you are using it for especially if only using a sub-feature).

 Also what you are trying to do, and what you want to achieve from the pygbag window ( both from localhost or real enabled dns ssl server).
