### ISSUE TITLE
use hardware acceleration for blitting

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/pygbag#146]
i tested both the pyglet and the pygame sample code on a older device (around 2010 chromebook) ,  the pyglet sample runs smooth in pygbag  , the pygame demo struggles a bit . i already have a large codebase using pygame (as i developed it first and worried about the web later)    would it be possible to hardware (webgl) accelerate some pygame functions

**Comment by pmp-p** [comment]
i don't intend to do that until wasm2/webgpu are everywhere. This should match pygame-ce going on SDL3.

Meanwhile you may want to look at ZenGL or Panda3D and use GLSL 300 (webgl2)

**Comment by tigercoding56** [comment]
> i don't intend to do that until wasm2/webgpu are everywhere. This should match pygame-ce going on SDL3.
> 
> Meanwhile you may want to look at ZenGL or Panda3D and use GLSL 300 (webgl2)
> 
> pyglet and moderngl won't be fully supported (either by me or actual mainteners)

thank you
