### ISSUE TITLE
Typo on index.html in wasm

### ISSUE THREAD

**Issue by briansbrian** [pygame-web/pygbag#159]
![Screenshot from 2024-03-06 12-13-48](https://github.com/pygame-web/pygame-web.github.io/assets/152048932/4132c066-1088-4d85-8c66-5e93ff0ddc9a)

THIS clears the error.
**style="z-index: 10;" style="background: #FFFFFF;"**

Anyways its awesome

**Comment by pmp-p** [comment]
fix in https://github.com/pygame-web/pygbag/commit/c99518bb2d8a96fb47930850db36232649088f74
