### ISSUE TITLE
cannot read the properties of undefined

### ISSUE THREAD

**Issue by Subisuresh321** [pygame-web/pygbag#162]
since i am using pygame and pygbag for my college project. and while i try to open my game in my website i get this error
![Screenshot (7)](https://github.com/pygame-web/pygbag/assets/162290234/811c9c03-28fa-4887-a215-1ca59ae9bb41)

the game works after reloading the page 2 or 3 times....but i cant submit this project with this error...is there any solution for this or can i modify that message and say "Reload the page" with  a reload button with it

**Comment by pmp-p** [comment]
You are not using the good address, use "localhost" special url in place of loopback "127.0.0.1"
