### ISSUE TITLE
raylib-python-cffi wheel

### ISSUE THREAD

**Issue by electronstudio** [pygame-web/pygbag#164]
I build a new release wheel, please add: https://github.com/electronstudio/pygbag-raylib/releases/download/v5.0.0.2/raylib-5.0.0.2-cp310-abi3-wasm32_bi_emscripten.whl

**Comment by pmp-p** [comment]
Thanks, done !
cdn will update soon, wheel will be visible for pygbag 0.9.x serie and git

**Comment by pmp-p** [comment]
@electronstudio on firefox that sample does not work well, maybe you know what's the problem https://pygame-web.github.io/showroom/pythongit.html#src/test_raylib_es3.py
![shot-2024-04-05_1712344540](https://github.com/pygame-web/pygbag/assets/16009100/618c5c26-94b6-4c15-b0ed-a60cefac37fb)

**Comment by electronstudio** [comment]
Did it work previously with the wheel you built?

**Comment by pmp-p** [comment]
no not on firefox/edge neither 5.0.0.1 or 5.0.0.2

chrome / brave  are ok
