### ISSUE TITLE
pythonrc.py missing 

### ISSUE THREAD

**Issue by Not1Sam** [pygame-web/pygbag#166]
i am trying to run my game in my website but when i try local host i only get a black-screen in the game window.
i made a simple game with no images or assets and it worked but now that i am try to run my tic tac toe game that is in python btw it seems to not work.
idk if there is a fix on my end if so please let me know.
PS: the console gives me the following error: 

    ERROR 404: https://pygame-web.github.io/archives/0.9/pythonrc.py
    127.0.0.1 - - [24/Apr/2024 13:49:00] code 404, message File not found
    127.0.0.1 - - [24/Apr/2024 13:49:00] "GET //archives/0.9/pythonrc.py HTTP/1.1" 404 -

**Comment by pmp-p** [comment]
try removing the "build" folder in the game folder before retry/update pygbag

**Comment by Not1Sam** [comment]
i did that like 5 times and it did not work same error

**Comment by pmp-p** [comment]
What is your pygbag version (python -m pygbag), python version, operating system and version + lang interface ?

Also what exact command line call did you run against the game ?

from the console i'd say you are not on 0.9.1 version because the file is now called cpythonrc.py  unlike earlier versions.

**Comment by Not1Sam** [comment]
So for the version its 0.9.1 the lates one and i ran the command that was in the doc "pygabag "the file path" but i think its pygbag running with pygame_gui because i coded a simple cube moving game and it worked.
A solution would be to not use pyg_gui but i need to for the text_input.

**Comment by pmp-p** [comment]
pygame_gui works fine with pygbag if you include the PEP 723 header correctly to install it along with the language support eg : 
https://pygame-web.github.io/showroom/pypad.html#src/test_pygamegui.py

**Comment by Not1Sam** [comment]
by header do u mean :

# /// script
# dependencies = [
#  "pygame-ce",
#  "pygame-gui",
#  "python-i18n",
# ]
# ///


and should i import i18n as well ?

**Comment by Not1Sam** [comment]
Nevermind it worked mate THANK YOU VERY VERY MUCH
