### ISSUE TITLE
Stuck on black screen

### ISSUE THREAD

**Issue by JrFellow** [pygame-web/pygbag#169]
So i have a car game that i want to post to itch.io or share to other people, so i wanted to convert it to the web using pygbag. But after trying it out i was stuck on a black screen. Here is my project and please help [me:](https://github.com/JrFellow/Code-RMR)

**Comment by larsbutler** [comment]
It looks like you're missing `await asyncio.sleep(0)` is in the correct places; the sleep needs to go inside each of your game loops (looks like you have several). For example, here: https://github.com/JrFellow/Code-RMR/blob/8022299a1caf5a26cf2023a206101dcd1b0e2476/main.py#L1292. Try adding a `await asyncio.sleep(0)` at the same indentation level as `clock.tick(app.fps)`, and then do the same for the other loops.

**Comment by JrFellow** [comment]
Hi Lars,

I’m excited to publish this game on the web and really appreciate your
excellent help. I’ll give your technique a try and let you know how it goes.

Thanks,
Liam.

**Comment by JrFellow** [comment]
Hi Lars,

I attempted your approach, but I'm encountering an error/warning when
using await
asyncio.sleep(0) at the same indentation level as clock.tick(app.fps).
Please see the attached screenshots for more details.
[image: image.png][image: image.png]

Could you suggest an alternate solution?

Thanks,
Liam

**Comment by pmp-p** [comment]
`await asyncio.sleep(0)` can only be called in an async function ( which should be the main game loop ). Your app design use nested pygame loops and this is generally bad practice better use game states that draw()/render() on a surface , and let main loop blit that surface. See https://github.com/pmp-p/pygame-breakout-wasm/tree/main for an example and https://github.com/pmp-p/pydew-valley-uzh-pygbag/ for a more complex one.
