### ISSUE TITLE
Pygame crashing in browser due to ImportError

### ISSUE THREAD

**Issue by Hunterclarg** [pygame-web/pygbag#171]
I was trying to port my pygame game to webassembly using pygbag, but I keep getting this error when using localhost:8000/#debug
Traceback (most recent call last):
     File "<console>", line 9, in <module>
ImportError: cannot import name 'events' from 'aio' (/data/data/org.python/assets/site-packages/aio/__init__.py). Did you mean: 'Event'?

For some reason, ctrl + c is overrun by KeyboardInterrupt, so I had to type in the error message by hand. TLDR there may be typos.

**Comment by Hunterclarg** [comment]
I managed to solve the issue, apparentely this particular error was something to do with nest_asyncio which I found after a google search as apparentely the only way to solve another issue I was having. Turns out not, because I just deleted those lines and never got the same error again. There were other errors, lots of them, which I managed to solve. Here are some helpful tips for anyone who is struggling also:

- use http://localhost:8000/?-i to test the game after compiling it, you get a debug window and a small game window in the corner. Otherwise you will not know if it crashed, this is the most helpful thing by far.
- await asyncio.sleep(0) must be in every game loop, everywhere where you are calling clock.tick()
- you have to make every function that has await asyncio.sleep(0) in it an async function by adding the keyword async before def.
- no pygame.quit() or other stuff after asyncio.run(main()), it should be the last line of code.
- the main file must be named main.py (allegedly, I did not care to find out)
- import numpy and other libs that are giving you errors right after importing pygame.
- If you have imported libraries into the same directory as your main function for some reason (i had to to compile my game to an .exe file), delete these files. For me at least they caused errors with importing from parent functions.

Good luck to any other poor souls who have issues with this.

**Comment by pmp-p** [comment]
from nest-asyncio :
![shot-2024-08-22_1724332113](https://github.com/user-attachments/assets/7d9a1bdf-2485-41fc-a6e8-d807d7cac964)

pygbag has a custom asyncio loop and falls into the "other" category
so maybe open an issue there or here.

**Comment by Hunterclarg** [comment]
No, the patch was only needed when testing on pc, when running on web it was fine. So I'm just commenting the nest_asyncio stuff away before compiling. I'll try the pyodide stuff, what exactly do you suggest? I've never heard of pyodide before.

**Comment by pmp-p** [comment]
pyodide is another version of cpython-wasm, but if do not need anymore "nest_asyncio" then no reason to go for it because it is really not currently optimized for pygame.
