### ISSUE TITLE
SyntaxError: missing } after function bodyxterm.js:1:32768 popup showing up after compilation (windows, firefox)

### ISSUE THREAD

**Issue by ServaSide** [pygame-web/pygbag#176]
i was making my game in python using pygame, then tried to compile it but nothing.. the bug appeared.the code was generated by the program (i suck at webdev so i dont know anything)

**Comment by pmp-p** [comment]
Sorry, in current state this is not a proper bug report. We cannot help you without more informations or whole project access, pygbag version, Operating system and browser client.
 Have a look to others usage problems reports https://github.com/pygame-web/pygbag/issues?q=is%3Aissue+label%3Ausage+
