### ISSUE TITLE
Does pygbag support any Chinese fonts?

### ISSUE THREAD

**Issue by pzy2000** [pygame-web/pygbag#178]
I tried to check with print("font", pygame.font.get_fonts()), but it seems that print info will not show on the web console.

**Comment by pmp-p** [comment]
you need to provide fonts in assets, load them see a test with arabic font here https://pygame-web.github.io/showroom/pypad_git.html#src/test_hb.py

**Comment by pzy2000** [comment]
> you need to provide fonts in assets, and load them manually before use. See a test with arabic font here https://pygame-web.github.io/showroom/pypad_git.html#src/test_hb.py
> 
> ref: #111

thx a lot!
