### ISSUE TITLE
sound may have problems ( please report )

### ISSUE THREAD

**Issue by pmp-p** [pygame-web/pygbag#19]
tested on https://pmp-p.itch.io/stuntcat for https://github.com/pygame/pygame/issues/718
_________________
Linux:
  - Firefox : OK
  - Brave : squeaky/sizzling  ( possibly: https://github.com/brave/brave-browser/issues/10619 )
_________________

Win:

Windows 8.1:
   - Firefox: OK but it seems that sounds are delayed
   - Brave: kind of squeaky/sizzling ( possibly: https://github.com/brave/brave-browser/issues/10619 )
  
Windows 11:
   - Edge: Sizzling/static sound alongside normal sound when focus. minimized the sound plays normally.
   - Brave: Sizzling/static sound alongside normal sound when focus. minimized the sound plays normally.
_________________
Osx:
_________________
Android:
_________________
iOS:

### most likely related (tldr webaudio is broken):

https://github.com/emscripten-core/emscripten/issues/11380
https://github.com/WebAudio/web-audio-api/issues/1322
https://github.com/WebAudio/web-audio-api/issues/1323

**Comment by Matiiss** [comment]
Windows 8.1
Firefox: sound quality: OK but it seems that sounds are delayed
Brave: sound quality: kind of squeaky/sizzling

**Comment by pmp-p** [comment]
Seems OpenAL is unaffected so it could be an SDL2 problem with audio api deprecation.

**Comment by 9und30** [comment]
Sound delayed and laggy for me for small game (working perfectly when not in web): https://9und30.itch.io/duzzle
github: https://github.com/9und30/Duzzle
Used .ogg files

**Comment by pmp-p** [comment]
yep bad sound on both firefox and brave under heavy system load.
i guess webaudio thread priority is not good in all browsers and probably won't get fixed soon in SDL2 due to lack of resources/interest, if i get some time i'll patch openal in for at least music backgrounds.

**Comment by pmp-p** [comment]
SDL2 model is not good enough for lowend + pygame. The pull model is not suitable for any load
everything explained here https://github.com/WebAudio/web-audio-api/issues/1322#issuecomment-329834464

**Comment by pmp-p** [comment]
i've made a patch for music which seems ok already on 0.1.3.

for next 0.1.4 
multichannel SFX is not so easy when playing the same sample over itself so it is not active by default
to activate use :
```py
import pygame
pygame.init()
try:
    pygame.mixer.SoundPatch()
except:
    pass
```
leaving this open because patch is very basic and may not stand for avanced use.

**Comment by FinFetChannel** [comment]
Hello, I was trying the patch because I had problems on edge and chrome, it fixes the audio but seem to interfere with other things, like, if I press a button the rendering stalls. On firefox it was fine before the patch, but after it stopped working
Tested on win 10

**Comment by pmp-p** [comment]
0.1.5 fixes sound problem so above snippet is no more required
but drawback is no more .wav format in assets

**Comment by pmp-p** [comment]
also on chrome 81.0.4044.83 SDL2 audio is broken
```
main.js:1 Uncaught TypeError: SDL2.audio.currentOutputBuffer.getChannelData is not a function
    at 4962205 (main.js:1:101376)
    at mainThreadEM_ASM (main.js:1:364593)
    at _emscripten_asm_const_int_sync_on_main_thread (main.js:1:364765)
    at wasm-function[16556]:0x80cc69
    at dynCall (main.js:1:195788)
    at ScriptProcessorNode.SDL2.audio.scriptProcessorNode.onaudioprocess (main.js:1:100542)
4962205 @ main.js:1
mainThreadEM_ASM @ main.js:1
_emscripten_asm_const_int_sync_on_main_thread @ main.js:1
(anonymous) @ main.wasm:1
dynCall @ main.js:1
SDL2.audio.scriptProcessorNode.onaudioprocess @ main.js:1
```
better whould probably be turn off sdl2 audio completely and remove linked code to free some space.

**Comment by pmp-p** [comment]
changing mixer init parameters + offloading music to browser seems to give good results enough
feel free to reopen if not the case

**Comment by ShivamKR12** [comment]
@pmp-p audio sound issue on Samsung Galaxy A17 5G , Android 16 , One UI 8.0 , on both Brave and chrome. Brave version 1.89.145 and chrome version 147.0.7727.111 

MRE : https://github.com/ShivamKR12/pwa 

Same issue with other pygbag games too, such as on itch.io ( e.g. https://finfetchannel.itch.io/snow-guardians )

The audio is all noisy and breaking. Works fine on desktop browsers ( both Brave and Chrome )

**Comment by ShivamKR12** [comment]
Alright, so the issue seems to have improved after i removed the hard cap of 60 FPS from the game ( replacing `click.tick(60)` with just `clock.tick()` ) and increased the auido buffer size from 512 to 1024 ( `pygame.mixer.pre_init(44100, -16, 2, 512)` to `pygame.mixer.pre_init(44100, -16, 2, 1024)` ). But, it's still not completely gone ! slightly bigger audio files are still having the audio breaking issue, though smaller than before.

**Comment by ShivamKR12** [comment]
Alright, so i tested and verified that this isn't a issue with the `pygbag-0.9.3` . Going back to `pygbag-0.9.2` still has the same audio issue on the broswer on android, But this time, the pwa completely stops playing any sounds.
