### ISSUE TITLE
replace spaces in game folder by '.'

### ISSUE THREAD

**Issue by pmp-p** [pygame-web/pygbag#25]
and lowercase all for archive name

**Comment by alagumuthiah** [comment]
Hi,

I would like to contribute to this issue. Correct me if I am wrong...From my understanding the game folder is the test folder. Could you please help me with more details on the issue?

And also how do i setup the project? I tried installed pygbag.. it gets installed but pygbag <game-folder> command doesn't work.. it shows command not found.

**Comment by pmp-p** [comment]
hi welcome, if you want to work on pygbag better not install it, but running directly from git tree clone like this (python 3.8+):
 `python3.10 -m pygbag  --template static/default.tmpl /full/path/of/main.py`

the problem with archive name should be around https://github.com/pygame-web/pygbag/blob/c1357873cd09a1120a3b08c8413b2029785b84a4/pygbag/app.py#L163

**Comment by DaniMorales97** [comment]
Solved in #45.
