### ISSUE TITLE
Games uploaded to itch.io can't regain keyboard focus after losing it

### ISSUE THREAD

**Issue by davidpendergast** [pygame-web/pygbag#33]
To reproduce:
1. Upload a game to itch.io that accepts keyboard inputs, following the wiki instructions here: https://pygame-web.github.io/wiki/pygbag/ (I used the `window-template-wip.tmpl` template).
2. After the game starts, click somewhere else on the page.
3. The game will lose keyboard focus (as expected), but won't regain it even when you click it (so the game essentially becomes unplayable).
(You can actually manually refocus it by hitting tab enough times, since that cycles focus through everything on the page).

I was able to fix this by adding some `window.focus()` calls to `index.html` :
```
    window.onload = function () {

        var wasmterm

        if (!config.xtermjs) {
            // xterm js placeholder
            wasmterm = { print : console.log, sixel : function(){}}
        } else {
            // it uses  document.getElementById('terminal') to get its host
            wasmterm = new WasmTerminal( "terminal", 100, 35 )

            window.xterm = wasmterm.xterm

        }

        pythonvm(wasmterm, config)
        
        window.focus(); // ADDED THIS
    }
    window.onclick = function () { window.focus(); }  // ADDED THIS
    </script>
```
Maybe those (or something similar) should be there by default?

**Comment by pmp-p** [comment]
is it fixed in 0.1.4 ?
( anyway please upgrade itch games so they use the versionned cdn url of 0.1.4 )

**Comment by davidpendergast** [comment]
Hmm it's hard to say because I can't seem to get a build to work on itch with version 0.1.4. It shows the loading bar, but then produces this partially black, partially powder blue, non-interactive display. See: [https://ghastly.itch.io/test-project](https://ghastly.itch.io/test-project), password = pw

This build was generated by running `pygbag webzone` (webzone being the name of the directory), with pygbag version 0.1.4, python version 3.10.5, and pygame version 2.1.2. It runs fine from localhost so I think it's some kind of security / permissions issue it's encountering on itch:
![image](https://user-images.githubusercontent.com/8991935/184793014-14b1f980-dc9d-4773-92a9-6fdfa8793e24.png)
(Blotted some things out bc I have no idea what this stuff is)

Here's a pristine version of the project as well:
[webzone.zip](https://github.com/pygame-web/pygbag/files/9347741/webzone.zip)

Hope this helps!

**Comment by pmp-p** [comment]
please could you add that one file https://pygame-web.github.io/archives/0.1.4/pythonrc.py
to your web.zip and reupload / restest.
 I think i made a mistake on template and that it is trying to get pythonrc.py (prebuilts) where it would expect custom.py (game)

**Comment by pmp-p** [comment]
nvm, your browser hides from you some debug info i got :
runpy.js?cpython3.11:251  GET https://v6p9d9t4.ssl.hwcdn.net/html/6345359/pythonrc.py 403

 it is indeed getting pythonrc from iframe source instead of cdn. uploading a fix right now

**Comment by pmp-p** [comment]
running in itch iframe should be fixed right now

**Comment by davidpendergast** [comment]
Awesome, thanks! The game seems to run properly now in 0.1.4, however the re-focusing issue does not seem to be fixed (with the default template, in Firefox at least). When you click outside the game area and then back inside, it still will no longer receive key inputs from that point onward. This can be observed in the example project I posted above.

**Comment by pmp-p** [comment]
> When you click outside the game area 

do you get the focus/blur events in javascript console when doing that ?

itch is a bit different from fullscreen windowed because the iframe is not a window and may not receive all events. Maybe a test for running inside iframe is required and a different logic

**Comment by pmp-p** [comment]
i only get the "blur" event on v8

**Comment by pmp-p** [comment]
i get the focus event only when hitting "tab" on v8 and then the keyboard works again.
i guess the windows onclick trick is the only way

**Comment by davidpendergast** [comment]
I think I'm seeing the same thing as you. Clicking outside the game area for the first time produces:
`221 DISCARD : blur {'isTrusted': True}`
Clicking inside prints nothing.
Tabbing focus back to the game produces:
`221 DISCARD : focus {'isTrusted': True}`
And clicking outside produces the blur event again.

**Comment by DaniMorales97** [comment]
I don't know if this might help:

When using CTRL + SCROLL with the mouse to adjust zoom on the web, the keyboard focus returns to the iframe.

Started searching for the issue and found people that might have solved it using `tabindex="0"` and `.focus()`:
https://github.com/novnc/noVNC/issues/506#issuecomment-134302378

I'm still learning about all this so I don't think I'm able to solve this on my own yet. However, if I finally get it I'll fix it and PR.

**Comment by pmp-p** [comment]
yeah the trick is to set a listener to do a .focus() when iframe gets selected by mouse click after it has lost focus ( blur event )
Then remove the listener to gain cpu cycles.

**Comment by FinFetChannel** [comment]
never perceived it before because i also have mouse controls on most games, those work fine, but keyboard indeed stops working, tested on itch
