### ISSUE TITLE
[FIXED] Uncaught RuntimeError: Aborted(OOM) -> do not load and keep in memory too much big images

### ISSUE THREAD

**Issue by HetorusNL** [pygame-web/pygbag#36]
During the loading of some data before starting my application (don't know the exact size, but tracemalloc reports roughly 10MB of used memory during local debugging) the application stops and a runtime error (OOM) is shown in the console.

The whole error log is shown here: https://pastebin.com/cUbVnhCd

Github repo of the code used (for reproduction): https://github.com/HetorusNL/kanaraimasu/tree/integrate-pygbag
Commit hash: 2fc2e725544a6a393181d038a3d2289dee550286

Versions:
Ubuntu 20.04.4 LTS on WSL2 on Windows 10
Python 3.8.10
VSCode 1.67.2

Screenshot of the error in the console:
![image](https://user-images.githubusercontent.com/17402329/183285199-67e3c6f0-bc35-455a-ada9-bb14f55de472.png)

If there is anything else I can do/provide for this issue, I'm happy to oblige.

**Comment by pmp-p** [comment]
i did not have time to investigate yet but i will,
meanwhile could you try to reduce screen size to 720p instead of 1080p ?

**Comment by HetorusNL** [comment]
I've tried using a smaller screen size but the behavior is the same unfortunately as can be seen below:
![image](https://user-images.githubusercontent.com/17402329/183301049-3c6cbadf-7f35-48e7-840e-d9e7b4cbd29e.png)

I'm currently on holiday so won't have much time to debug the exact location in the python application where this happens.

Based on nothing concrete, but I see a lot of recurring lines in the stack trace, could this be something involving a recursive call in pygbag or on my end?

**Comment by pmp-p** [comment]
> could this be something involving a recursive call in pygbag or on my end?

either a recursive call in python loader part or your code, or repeated memory leak

**Comment by HetorusNL** [comment]
I have a different question, is it possible to make the python print(..) statements end up in the javascript console (or some other debug functionality) ?

**Comment by pmp-p** [comment]
just add #debug to url, like http://localhost:8000/#debug in local mode and the terminal should appear and canvas should be divided to half the page on top right.

**Comment by HetorusNL** [comment]
The cause seems to be found, depending on the settings (and a bug on my end*) the code loads 0, 1 or 2 times a large PNG image (PNG image data, 6000 x 3750, 8-bit/color RGBA, non-interlaced -> 90MB RGBA raw data).

Loading such an image 0 or 1 time is fine, but loading two of those images causes the OOM RuntimeError.

*The bug on my end involved always loading the images before checking the settings(file) whether they should be loaded, e.g. user selected it.

Some back story relating to the app: it consists of a application learning to write Japanese kana/kanji, and the application has the 'correct writings' stored in the PNG images, so they are required for the application to work properly. Each character represents a roughly 500x625 pixels section of the total image and the specific section is drawn from the 90MB loaded image.

Is it possible to request more memory from WASM/browser, or a way to reduce the impact of large images in WASM?

Small remark: also tested it in Chrome, it has the same behavior as Firefox while loading 2 images.

**Comment by pmp-p** [comment]
The way browser load png (internally it's literrally TGA format) it's unlikely to be solved with such sizes

You could switch to SVG, pygame dev can display them fine and should take much less memory ( but creating svg is a bit more difficult).

or make an array of png and load/unload on demand (simpler and backward compatible with all pygame versions).

**Comment by HetorusNL** [comment]
The switch to SVG didn't make a difference, although the SVG size was much much smaller (few KB instead of ~1MB), loading the SVG still caused the same issue at runtime.

I did fix it by preparing/caching the assets, as you suggested, one at a time. And the game logics load a single small PNG when it's about to be drawn on the screen, and is removed afterward.
