### ISSUE TITLE
Error about Folder names and --help function

### ISSUE THREAD

**Issue by N0t3nl1sh** [pygame-web/pygbag#42]
Pygbag version is 0.1.4

C:\Users\Acer\PROJECTS>pygbag PyWasm --help
this command doesn't work and gives this error:
ERROR: Last argument must be app top level directory, or the main python script

C:\Users\Acer\PROJECTS>pygbag PyWasm
But this command works fine even though they should output the same result.

**Comment by N0t3nl1sh** [comment]
Edit: oh wait i was doing it wrongly I should have done it like this: pygbag --help PyWasm

**Comment by pmp-p** [comment]
yeah it's a bit confusing but no last argument must indeed be folder or main.py because the help is for showing the path and default names that will be used.
so should be called like that
`C:\Users\Acer\PROJECTS>pygbag --help PyWasm`
