### ISSUE TITLE
[fixed] 0.1.5 itch.io zip might be broken => no more .wav !

### ISSUE THREAD

**Issue by Notenlish** [pygame-web/pygbag#43]
both on 0.1.5 and 0.1.4 running it in a test server works fine.
But making an itch.io zip in 0.1.5 seems to be broken, while 0.1.4 works fine

I uploaded the test project to here: https://github.com/N0t3nl1sh/Pygbag-0.1.5-test-game
Note: the itch.io build in that repository is 0.1.4

**Comment by pmp-p** [comment]
thx for help on discord tracking the source, 

i added a note to the [frontpage](https://pygame-web.github.io) explaining why wav format is no more supported.

leaving this open for anyone having the same problem.

**Comment by pmp-p** [comment]
now pygbag yell in the console when it find mp3/wav
