### ISSUE TITLE
Support for dearpygui

### ISSUE THREAD

**Issue by Equilibrier** [pygame-web/pygbag#48]
Would it be possible dearpygui also works with pygbag, out-of-the-box or wuth minor modifications to pygbag? As far as I know, dearpygame doesn't use pygame internally, for rendering purposes.

**Comment by pmp-p** [comment]
does dearpygui already has a wasm port ?

if not, as it would be quite an effort, there are already some gui that runs with pygame.

if you don't want to spend time/money on making a gui work, i'd suggest you select one that already work on canvas and use canvas postprocessing with alpha channel to overlay it other the pygame canvas.
