### ISSUE TITLE
 sqlite3

### ISSUE THREAD

**Issue by GrayWagner** [pygame-web/pygbag#49]
Hi, I am using sqlite3 as a basic database for a project. However, I am getting this error: ModuleNotFoundError: No module named sqlite3. 

Is it possible to get sqlite3 added?

Thanks
Gray

**Comment by pmp-p** [comment]
i think you just need to add the stdlib "sqlite3" module to your app you should find it in `lib/python3.11/sqlite3` of any python3.11 distribution.

The required binary module _sqlite3 is already linked  in 3.11 / 3.12 and should load
nb: i did not run any tests on it so please report your experience :)

**Comment by GrayWagner** [comment]
thanks man, yeah it worked. All i had to do was change: **import sqllite3** to **import _sqlite3**

**Comment by pmp-p** [comment]
Are you sure everything works as expected ? What is sqlite3.py from stdlib for then ?

**Comment by GrayWagner** [comment]
hey man, not sure why it works, but it has worked fine since.

**Comment by pmp-p** [comment]
so be it !
