### ISSUE TITLE
File paths need to be updated for the 0.7 version

### ISSUE THREAD

**Issue by kmenesesc** [pygame-web/pygbag#59]
When installing through the latest version (0.7.0; you get this version when following the recommended "pip install git+https://github.com/pygame-web/pygbag --user --upgrade"), the pygbag command references https://pygame-web.github.io/archives/0.7/favicon.png and https://pygame-web.github.io/archives/0.7/default.tmpl which don't exist. Even after manually providing the default.tmpl locally, the server still hangs because it can't find favicon.png so the client window hangs indefinitely waiting for favicon.png.

**Comment by pmp-p** [comment]
seems that cmdline is coming from the discord pygame pin, did you also add `--cdn https://pygame-web.github.io/pygbag/0.7/` as specified ?
