### ISSUE TITLE
pygame_gui port: RuntimeError: The FreeType 2 library hasn't been initialized

### ISSUE THREAD

**Issue by gabriel-v** [pygame-web/pygbag#64]
Inspired by [this fork here](https://github.com/pmp-p/pygame-gui-wasm) I wanted to try out `pygame_gui` because it looks really shiny.

After hacking it a bit, I came across this problem:

```
Traceback (most recent call last):
  File "/data/data/interfatza-pygame-gui/assets/pygame_gui/core/utility.py", line 405, in load
    self.loaded_font = Font(self.location, self.size, resolution=72)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The FreeType 2 library hasn't been initialized
```

We can reproduce it in any `#debug` terminal in the browser:
```
>>> import pygame.freetype
>>> pygame.freetype.init()
>>> pygame.freetype.get_init()
True
>>> pygame.freetype.Font('pygame_gui_data/FiraCode-Regular.ttf')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
RuntimeError: The FreeType 2 library hasn't been initialized
```

Doesn't matter if you initialize freetype in the main.py top block, or in the async main, or just before use - Python thinks it's initialized, but the C bindings underneath are not.

This problem has been reached in the "penguins can't fly" game port, [explained very clearly](https://github.com/pmp-p/pygame-PenguinsCantFly-wasm/blob/4072114d6d625d453e8d9786fcca0f7483d54c35/main.py#L154-L166).

I found the specific error [in pygame's C wrapping of freetype](https://github.com/pygame/pygame/blob/93a907c81e79558ed3a067c1726381da0a24020c/src_c/freetype/ft_wrap.h#L248) and [it might be related to threading?](https://stackoverflow.com/questions/18580810/library-not-initialized-in-python-pygame/18658564#18658564) I would suspect the asyncio green threads to cause this.

Anyway, I tried to [wrap `pygame.freetype.Font` using `pygame.font.Font`](https://github.com/gabriel-v/python-wasm-pygame-experiments/blob/db9fe41fbb1c5926ee955908c1d6bde3d5c45ce1/src/interfatza-pygame-gui/superduperfont.py#L4), but didn't do so correctly, so text does not show up.

Questions:
- Did you get the pygame-gui-wasm fork to work?
- Do you have any tips for implementing `pygame.freetype.Font` using `pygame.font.Font`?
- Any hacks you think we can make in pygame's freetype code, to maybe run the initializer on every [Font constructor](https://github.com/pygame/pygame/blob/c815dc747a886a84436c821eaa6fb7f5646663d5/src_c/_freetype.c#L1931), instead of crashing? After all, there's only so many fonts one can load, a little memory leak has never hurt a video game

P.S. I wrote the comment for this issue yesterday, and probably forgot to click "send" -- if you already deleted its duplicate, I apologize.

**Comment by gabriel-v** [comment]
I also found some theoretical discussions about [freetype 2 thread safety](https://github.com/behdad/ftthread) and this [email thread from 2003](https://lists.gnu.org/archive/html/freetype/2003-04/msg00055.html) - freetype 2 is not reentrant, and they suggest using one instance per thread.

I guess the next step here is to edit `ft_wrap.c` and `ft_wrap.h` to initialize the library and store it in the `Font` python object instead of the [static python module memory](https://github.com/pygame/pygame/blob/93a907c81e79558ed3a067c1726381da0a24020c/src_c/freetype/ft_wrap.h#L240-L241)

**Comment by pmp-p** [comment]
i did not delete but transfered here https://github.com/pygame-web/pkg-porting-wasm/issues/1
since it's not a pygbag issue, it's either a pygame or pygame_gui porting

**Comment by gabriel-v** [comment]
I knew I clicked send!

thanks for clarification
