### ISSUE TITLE
better documentation as to what is supported

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/pygbag#75]
right now to find if a module is suported you need to go to pygbag's github find the link to the module list and see if your module is in there , also to find a generic module that does something like  text manipulation for example you need to basically test like 10 modules ,

my proposal is to make a documentation page that shows  supported modules , types of modules (like any text related modules that are supported , any GUI ones , any image manipulation ones - for instance)   and also 

documents what functionality differs if any  it should also list some common python things ( like looping over all files in a directory ) and show ways to archive them both on the server  (if they differ from normal python way to do them else it should leave a remark that they are the same) (looping over a game-data directory for example ) and the client (asking client to upload directory to loop over)

**Comment by pmp-p** [comment]
hi, i think that page has already begun here https://pygame-web.github.io/wiki/pkg . Note that i usually have no idea if the module is well supported. If someone ask for it i try to build it, correct the obvious if need but it's up to people requesting the module to test it : because i count on them to have a real usecase . In our case testsuites are not mandatory.

Partial support can get things done.
it would just be perfect that people help fill the wiki page after testing.

**Comment by tigercoding56** [comment]
> hi, i think that page has already begun here https://pygame-web.github.io/wiki/pkg . Note that i usually have no idea if the module is well supported. If someone ask for it i try to build it, correct the obvious if need but it's up to people requesting the module to test it : because i count on them to have a real usecase . In our case testsuites are not mandatory.
> 
> Partial support can get things done. it would just be perfect that people help fill the wiki page after testing. Anyone wanting to join the porting team ( or wiki for just validating packages ) you are welcome on pygame-community discord you will find me there as well as people with prior pygbag experience.
> 
> Can't go faster than the train anyway, and we are still ahead of pypi index because we already host binary modules.
> 
> For now only pure python compatible with wasm will be listed see discussion here https://discuss.python.org/t/do-we-want-classifiers-for-webassembly-on-pypi/22712/4

ok   Ty  .
