### ISSUE TITLE
Pygbag firebase_admin not found

### ISSUE THREAD

**Issue by that1mortal** [pygame-web/pygbag#79]
When I launch pygbag I try to use firebase, it says in the debug:
`PKG NOT FOUND : want='firebase_admin', resume=<function <module> at 0x81ef88>, ex=ModuleNotFoundError("No module named 'firebase_admin'")`
Is there a way to fix this or is Firebase just not supported?

**Comment by pmp-p** [comment]
requests for extra modules goes https://github.com/pygame-web/pkg-porting-wasm as they are outside pygbag scope which is packaging not compilation (yet).
