### ISSUE TITLE
when running in browser game not responding to mouse clicks

### ISSUE THREAD

**Issue by Meron-Gelbard** [pygame-web/pygbag#81]
Please help. 
when running locally the game works fine (with a local OS window) but when served through pygbag on a webpage the game doesnt respond to mouse clicks.
i have the listener set perfect in my game loop...
what am i doing wrong?

**Comment by pmp-p** [comment]
what game is this about ? please show some code, there are various mouse modes it depends on kind of game so hard to guess ...

**Comment by Meron-Gelbard** [comment]
hi thanks!
im using:
for event in pygame.event.get():
    if event.type == pygame.MOUSEBUTTONDOWN:

then accessing the mouse position from:   event.pos
i also tried accessing position from pygame.mouse.get_pos()

both work fine when running locally through pycharm but when served on a webpage via localhost:8000 
using pygbag the game doesn't seem to respond. 

i might be having a totally different problem that makes the game stuck all together but i'm not sure as the basic interaction is using the mouse click.
anyway i should say again that locally everything works fine...

**Comment by pmp-p** [comment]
if you don't show your main.py we cannot help you, the fact that game is running locally does not means it will run on web "out of the box", especially if you have a wrong update loop see https://pygame-web.github.io/wiki/python-wasm/#main-loop-async

**Comment by pmp-p** [comment]
not enough information to give a solution, most likely missing async loop
