### ISSUE TITLE
pygame ce is not the latest version, no FRects

### ISSUE THREAD

**Issue by yolowex** [pygame-web/pygbag#83]
![image](https://user-images.githubusercontent.com/122750743/231843241-cf339508-d748-4fe9-9e64-dc952f8d219c.png)

without FRect's my project as a whole is broken.
why don't you make it so your project always uses the latest version of pygame-ce?

**Comment by pmp-p** [comment]
I'm just busy atm, i'll update asap. Sure, continuous integration with pygame-ce would be possible but only with a browser testsuite ( eg using playwright ) but there's no manpower to achieve that currently. Anyone is welcome to help :)

**Comment by mmdmoa** [comment]
thanks for the info, I have enough time to help, but not some of the experties. you can check my repo to see if I am fit to contribute to your project in this issue, I would be happy to help!

**Comment by pmp-p** [comment]
The git version has FRect try it with prepending `--cdn https://pygame-web.github.io/pygbag/0.0/` on the cmdline and confirm it work fine.

**Comment by mmdmoa** [comment]
sorry for the late, I will check it out asap

**Comment by pmp-p** [comment]
pygame-ce wheel was updated, pygbag 0.7 has FRect ( that include already published software )
