### ISSUE TITLE
urllib failed to get pygame-wasm.github.io/archives/0.7

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/pygbag#91]
pygbag gives me this error
![image](https://user-images.githubusercontent.com/90169211/236584279-35af1383-49be-4872-a6e0-1dfff1bb4c21.png)
even though i can connect to pygame-web.github.io
![image](https://user-images.githubusercontent.com/90169211/236584325-457a2d4d-d8ed-4fd7-970f-df14e7943c0f.png)

**Comment by pmp-p** [comment]
it's probably a temporary network of some kind, or a misconfigured transparent proxy on the line. i think that is not fixeable on pygbag side
