### ISSUE TITLE
Playing sound file example missing in main/test

### ISSUE THREAD

**Issue by BabaKofiFHDA** [pygame-web/pygbag#93]
I need an example of playing sounds. In
[https://github.com/pygame-web/pygbag/tree/main/test/sfx](https://github.com/pygame-web/pygbag/tree/main/test/sfx)
there is a beep.ogg, but there is no example in the main.py at
[https://github.com/pygame-web/pygbag/blob/main/test/main.py](https://github.com/pygame-web/pygbag/blob/main/test/main.py)
for how to play it with the pygame mixer.

**Comment by larstuff** [comment]
I might not be the expert on this, but it does work, I used it a simple project that is more or less a clone of an Udemy course on pygame. You can view it on https://naturfagmoro.com/pygbag/

# I learned it the course that You first load the sound into the mixer, using:
sound = pygame.mixer.load("yoursound.ogg")
# Then to play it, use:
sound.play()

The project mentioned above is at github:
https://github.com/larstuff/pygbag-test-2023/tree/pybagger

**Comment by pmp-p** [comment]
minimal test does not use audio because of browser restrictions on sound play without user authorization. Use full pygame examples and the default template for that.
