### ISSUE TITLE
About add custom themes to pygbag

### ISSUE THREAD

**Issue by cool-dev-guy** [pygame-web/pygbag#94]
**Adding custom themes**
I would like to add custom themes to `pygbag` can you please tell me where the `index.html` file used on packaging is created/modified?

**Comment by pmp-p** [comment]
the index.html is generated from a mix of python and html code which you can find in the .tmpl files hosted in archives. You can get a copy of them edit them locally and then override them on pygbag command line by prepending `--template` and relative path of the file.

0.7 files : https://github.com/pygame-web/archives/tree/main/0.7

git files : https://github.com/pygame-web/pygbag/tree/gh-pages/0.0

**Comment by pmp-p** [comment]
editing template is for avanced user so no need to document that for now

it is preferable to fix default templates when they don't fit well generic use
